Repository OpenGammaProject/Gamma-MCA, pull requests merged in 2023-07, with the labels that each got.

#121 Version 2023-07-06
  assets/js/main.js
  assets/js/main.js.map
  package-lock.json
  package.json
  service-worker.js
  source/main.ts
Labels: security

#123 Version 2023-07-08 Hotfix
  assets/js/main.js
  assets/js/main.js.map
  index.html
  source/main.ts
Labels: bug, enhancement

#129 Version 2023-07-23
  .github/workflows/eslint.yml
  assets/js/main.js
  index.html
  package-lock.json
  package.json
  service-worker.js
  source/main.ts
Labels: enhancement
